version: '3'
services:
  vsftpd:
    image: panubo/vsftpd
    environment:
      - FTP_USER=adminFTP
      - FTP_PASSWORD=adminFTP
    volumes:
      - /home/vagrant/pruebaFTP:/srv
    expose:
      - 21
    network_mode: host